name: deploy-cloud-function
description: "Run tests and deploy Cloud Function on push to deploy/cloud-function"

repositoryEventConfig:
  repository: projects/git-release-496817/locations/europe-west9/connections/git-release-repo/repositories/camlebrun-git-release
  push:
    branch: "^deploy/cloud-function$"

gitFileSource:
  path: cloudbuild.yaml
  repoType: GITHUB
  repository: projects/git-release-496817/locations/europe-west9/connections/git-release-repo/repositories/camlebrun-git-release
