GCP_PROJECT = "git-release-496817"
GCP_REGION = "europe-west9"

R2_BUCKET = "git-release-releases"

MAX_RELEASES_PER_RUN = 50
BACKFILL_NON_SEMVER = 20
DIGEST_DEFAULT_LIMIT = 200
DIGEST_MAX_LIMIT = 500
LLM_MAX_TOKENS = 4096
MISTRAL_MODEL = "mistral-small-latest"

GITHUB_API_BASE = "https://api.github.com"
GITHUB_TIMEOUT_S = 10
GITHUB_RETRY_MAX = 3
