GCP_PROJECT = "git-release-496817"
GCP_REGION = "us-central1"

R2_BUCKET = "git-release-releases"

MAX_RELEASES_PER_RUN = 50
BACKFILL_NON_SEMVER = 20
DIGEST_DEFAULT_LIMIT = 20
DIGEST_MAX_LIMIT = 100
LLM_MAX_TOKENS = 1024
GROQ_MODEL = "llama-3.3-70b-versatile"
GITHUB_API_BASE = "https://api.github.com"
GROQ_TIMEOUT_S = 10
GITHUB_TIMEOUT_S = 10
GITHUB_RETRY_MAX = 3
